export const MEALS = [
  { id: 1, name: 'Pancakes & Maple Syrup', description: 'Fluffy golden pancakes served with rich maple syrup and butter', price: 150, image_url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=600&q=80', category: 'breakfast', quantity_available: 30, availability: true },
  { id: 2, name: 'Spanish Omelet', description: 'Three-egg omelet with tomatoes, onions, bell peppers and cheese', price: 100, image_url: 'https://images.unsplash.com/photo-1510693060754-07e0ea94f5fb?auto=format&fit=crop&w=600&q=80', category: 'breakfast', quantity_available: 25, availability: true },
  { id: 3, name: 'Mandazi & Tea', description: 'Crispy East African doughnuts served with a cup of hot milk tea', price: 80, image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80', category: 'breakfast', quantity_available: 40, availability: true },
  { id: 4, name: 'Chicken Pilau', description: 'Aromatic spiced rice cooked with tender chicken chunks and pilau masala', price: 200, image_url: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=600&q=80', category: 'lunch', quantity_available: 35, availability: true },
  { id: 5, name: 'Chapati & Beans', description: 'Soft layered flatbread served with well-spiced kidney beans stew', price: 120, image_url: 'https://plus.unsplash.com/premium_photo-1663089688180-2a3a0e6981be?auto=format&fit=crop&w=600&q=80', category: 'lunch', quantity_available: 40, availability: true },
  { id: 6, name: 'Rice & Chicken Stew', description: 'Steamed white rice served with a rich tomato-based chicken stew', price: 180, image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80', category: 'lunch', quantity_available: 30, availability: true },
  { id: 7, name: 'Ugali & Beef Stew', description: 'Traditional ugali paired with slow-cooked tender beef stew and vegetables', price: 160, image_url: 'https://images.unsplash.com/photo-1625937175440-cc5441d6b1d4?auto=format&fit=crop&w=600&q=80', category: 'lunch', quantity_available: 45, availability: true },
  { id: 8, name: 'Pasta Bolognese', description: 'Al dente penne pasta in a rich tomato and minced beef sauce', price: 220, image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?auto=format&fit=crop&w=600&q=80', category: 'supper', quantity_available: 20, availability: true },
  { id: 9, name: 'Githeri Special', description: 'Mixed maize and beans slow-cooked with tomatoes, onions and spices', price: 100, image_url: 'https://images.unsplash.com/photo-1540914124281-342587941389?auto=format&fit=crop&w=600&q=80', category: 'supper', quantity_available: 35, availability: true },
  { id: 10, name: 'Sukuma Wiki & Ugali', description: 'Collard greens sautéed with onions, served with ugali and fried fish', price: 130, image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80', category: 'supper', quantity_available: 40, availability: true },
];

export const MOCK_ORDERS = [
  { id: 'ORD-001', user_id: 'STUD123', guest_name: null, phone_number: '0712345678', status: 'paid', total_amount: 200, created_at: new Date().toISOString(), items: [{ meal_id: 4, quantity: 1, name: 'Chicken Pilau' }] },
  { id: 'ORD-002', user_id: null, guest_name: 'Jane Doe', phone_number: '0798765432', status: 'preparing', total_amount: 300, created_at: new Date().toISOString(), items: [{ meal_id: 5, quantity: 2, name: 'Chapati & Beans' }, { meal_id: 2, quantity: 1, name: 'Spanish Omelet' }] },
  { id: 'ORD-003', user_id: 'STUD456', guest_name: null, phone_number: '0755001234', status: 'ready', total_amount: 180, created_at: new Date().toISOString(), items: [{ meal_id: 6, quantity: 1, name: 'Rice & Chicken Stew' }] },
];
